---
# defaults file for docker
pakages_list:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
docker-eng:
  - docker-ce
  - docker-ce-cli
  - containerd.io

