---
# tasks file for nginx
- name: insatall ngninx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: Deploy Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
