---
# tasks file for docker
- name: Install required system packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - "{{ pakages_list }}"
    tags:
      - pakage

- name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: Add Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
      filename: docker

- name: Install Docker Engine
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - "{{ docker_eng }}"
    notify: restart docker
    tags:
      - installdocker

- name: Add vagrant user to docker group
    user:
      name: vagrant
      groups: docker
      append: yes

- name: Enable and start Docker service
    systemd:
      name: docker
      enabled: yes
      state: started
